name: Login
oauth2:
  GitHub:
    clientID: your_client_id
    clientSecret: your_client_secret
    clientIDParamName: client_id
    clientSecretParamName: client_secret
    redirectUri: http://localhost:8080/login/callback
    redirectUriParamName: redirect_uri
    accessTokenUri: https://github.com/login/oauth/access_token
    authorizationUri: https://github.com/login/oauth/authorize
    userdataUri: https://api.github.com/user
