name: Login
oauth2:
  GitHub:
    clientID: 155d793cd71173b6ca6a
    clientSecret: f5dda2ef42f7e0b4ec25f648a4f0e0ccb77e7b38
    clientIDParamName: client_id
    clientSecretParamName: client_secret
    redirectUri: http://localhost:8080/login/callback
    redirectUriParamName: redirect_uri
    accessTokenUri: https://github.com/login/oauth/access_token
    authorizationUri: https://github.com/login/oauth/authorize
    userdataUri: https://api.github.com/user
